site_name: AURlabCVsimulator
pages:
- Home: index.md
- About: about.md
- Find center of object: findCenterOfObject.md
- Create disparity map: Disparity_map.md
- Look at the LBP histogram: PlotLBPsHistogram.md
- Train the lbp model: TrainModelLbp.md
- Predict the lbp model:  PredictWithModelLbp.md
- Look at the Haralick histogram: PlotHaralickHistogram.md
theme: readthedocs
